version: "2"
linters:
  enable:
    - misspell
    - revive
    - sloglint
  settings:
    errcheck:
      exclude-functions:
        - io.Copy
        - (net/http.ResponseWriter).Write
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  exclusions:
    generated: lax
