go:
    # This must match .circle/config.yml.
    version: 1.25
repository:
    path: github.com/prometheus-community/pushprox
build:
    binaries:
        - name: pushprox-client
          path: ./cmd/client
        - name: pushprox-proxy
          path: ./cmd/proxy
tarball:
    files:
        - LICENSE
